### PR TITLE
BLD: prototype of triage form

### PR DESCRIPTION
**Pull request by lacabra**
Implemented a first functional prototype of the triaging form in the landing page. It only allows the user to select one item in each category (akin to a radio button), for each of the 4 questions, and the button at the bottom of the form only becomes active when a choice has been made for each category (otherwise is disabled and cannot be clicked).

Once the button is enabled, an alert message informs you of your choices (this is only to show that the answers are recorded, and a decision tree can be implemented to redirect the user based on their choices)

I have chosen to display all the questions in one screen so that the user has a perspective of all questions that will be asked of them, however an alternative would be to paginate the questions, and only ask one question per display (with the downside that if the user wants to change their answers, they have to navigate back and forth between the 4 displays). For a example of what the "pagination" would look like, take a look at this other (unrelated) [form](https://digitalpublicgoods.net/eligibility/).

Screenshot of the initial state of the form, all options unselected, and button at the bottom disabled:

Screen Shot 2021-10-21 at 3 02 18 PM

Screenshot of form with an option selected for each category and bottom button enabled:

Screen Shot 2021-10-21 at 3 03 18 PM

Screenshot of temporary alert message informing user of their choices:

Screen Shot 2021-10-21 at 3 04 30 PM

### CODE REVIEW

**Comment by eduinnovation** [comment]
@lacabra  wondering if you can add "Other OS LMS" as an option and then I'll approve?

**Comment by lacabra** [comment]
@eduinnovation added requested option for `Other open-source LMS` in a026b33 as requested above, and as seen in the screenshot below:

Screen Shot 2021-11-30 at 12 17 30 PM

**Comment by eduinnovation** [comment]
@lacabra  thanks! Can we go ahead and deploy? Also - how do we now link the answers of this to the pages?

**Comment by lacabra** [comment]
@eduinnovation: this has now been deployed, and you can see it live at https://unicef.github.io/ai-toolkit/

If you tell me each of the pages each combination of answers needs to be directed to, I will code it in.

**Pull request merged**
